# Generated by Django 5.0.2 on 2024-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('school_level', models.CharField(max_length=100)),
                ('health_issue', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
